### ISSUE TITLE
run script is not executable?

### ISSUE THREAD

**Issue by calroc** [PhoenixBureau/mal#1]
```
sforman@ubuntu-s-1vcpu-1gb-sfo3-01:~/mal$ make "test^nim-too^step0"
(call STEP_TEST_FILES,nim-too,step0): impls/tests/step0_repl.mal
----------------------------------------------
Testing test^nim-too^step0; step file: , test file: tests/step0_repl.mal
Running: env STEP=step0_repl MAL_IMPL=js ../../runtest.py  --deferrable --optional   ../tests/step0_repl.mal -- ../nim-too/run
Traceback (most recent call last):
  File "../../runtest.py", line 230, in <module>
    r = Runner(args.mal_cmd, no_pty=args.no_pty, line_break="\r\n" if args.crlf else "\n")
  File "../../runtest.py", line 102, in __init__
    self.p = Popen(args, bufsize=0,
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '../nim-too/run'
make: *** [Makefile:410: test^nim-too^step0] Error 1


sforman@ubuntu-s-1vcpu-1gb-sfo3-01:~/mal$ ls -l impls/nim-too/run
-rw-rw-r-- 1 sforman sforman 57 Jan  3 23:10 impls/nim-too/run
```

**Comment by calroc** [comment]
```
$ chmod +x impls/nim-too/run
```

fixed that and progress was made...
